# Generated by Django 5.0.3 on 2024-06-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='meeting_pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meeting_images/')),
                ('type', models.CharField(blank=True, choices=[('bod', 'BOD'), ('hr', 'HR'), ('finance', 'Finance'), ('audit', 'Audit'), ('agm', 'AGM'), ('procurement', 'Procurement')], max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('pdf', models.FileField(blank=True, default=None, null=True, upload_to='pdfs/')),
                ('add_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='Dashboard.bodmeeting')),
            ],
            options={
                'verbose_name_plural': 'AddAgendas',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_image/')),
                ('name', models.CharField(max_length=255)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.department')),
                ('designation_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.designation')),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
    ]
