# Generated by Django 5.0.3 on 2024-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_agenda_options_alter_member_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name_plural': 'AddAgendas'},
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='SubAgenda',
        ),
    ]
