# Generated by Django 5.0.3 on 2024-06-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_agenda_options_alter_member_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subagenda_title', models.TextField(blank=True, null=True)),
                ('subagenda_description', models.TextField(blank=True, null=True)),
                ('subagenda_decision', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='sub_agenda_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agendas', to='Dashboard.agenda')),
            ],
        ),
    ]
