# Generated by Django 5.0.3 on 2024-06-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_subagenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subagenda',
            old_name='subagenda_decision',
            new_name='subagenda_descision',
        ),
        migrations.RemoveField(
            model_name='subagenda',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='subagenda',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='subagenda_pdfs/'),
        ),
    ]
