# Generated by Django 5.0.3 on 2024-07-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_rename_subagenda_decision_subagenda_subagenda_descision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Dashboard.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_sub_Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subagenda_title', models.CharField(max_length=50)),
                ('subagenda_description', models.TextField(blank=True, null=True)),
                ('subagenda_descision', models.TextField(blank=True, null=True)),
                ('sub_sub_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='Dashboard.subagenda')),
            ],
            options={
                'verbose_name_plural': 'Sub_sub_Agenda',
            },
        ),
    ]
