# Generated by Django 5.0.3 on 2024-07-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_notifications_sub_sub_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='chairman',
        ),
        migrations.AddField(
            model_name='notifications',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Dashboard.member'),
        ),
    ]
