# Generated by Django 5.0.3 on 2024-07-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_notifications_chairman_notifications_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_Membors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.notifications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.member')),
            ],
        ),
    ]
