# Generated by Django 5.1.1 on 2024-10-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_minutesofmeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BODMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bod_members', to='Dashboard.member')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bod_member_notifications', to='Dashboard.notifications')),
            ],
        ),
    ]
