# Generated by Django 5.1.1 on 2024-10-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_bodmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodmember',
            name='members',
            field=models.ManyToManyField(related_name='selected_members', to='Dashboard.member'),
        ),
        migrations.AlterField(
            model_name='bodmember',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bod_member_notifications', to='Dashboard.notifications'),
        ),
    ]
