# Generated by Django 5.1.1 on 2024-10-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_bodmember_members_alter_bodmember_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notifications/pdfs/'),
        ),
    ]
