# Generated by Django 4.2.13 on 2024-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_userviewpermission_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewpermission',
            name='view_name',
            field=models.CharField(choices=[('pro_meetings', 'Pro Meetings'), ('Au_meetings', 'AU Meetings'), ('fn_meetings', 'Finance Meetings'), ('hr_meetings', 'HR Meetings'), ('agm_meeting', 'AGM Meeting'), ('all_meetings', 'All Meetings')], max_length=100),
        ),
    ]
