# Generated by Django 5.1.2 on 2024-10-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_alter_userviewpermission_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewpermission',
            name='view_name',
            field=models.CharField(choices=[('pro_meetings', 'Pro Meetings'), ('Au_meetings', 'AU Meetings'), ('fn_meetings', 'Finance Meetings'), ('hr_meetings', 'HR Meetings'), ('agm_meeting', 'AGM Meeting'), ('all_meetings', 'All Meetings'), ('meeting_details', 'meeting_details')], max_length=100),
        ),
    ]
