# Generated by Django 5.1.2 on 2024-10-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0020_useractivitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
