# Generated by Django 5.1.2 on 2024-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0021_delete_somemodel_delete_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='short_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
