# Generated by Django 5.1.2 on 2024-10-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0025_bodmeeting_updated_by_bodmember_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
