# Generated by Django 5.1.2 on 2024-10-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodmeeting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bodmember',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='minutesofmeeting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
