# Generated by Django 5.1.2 on 2024-10-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0028_bodmeeting_updated_by_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='member_resumes/'),
        ),
    ]
