# Generated by Django 5.1.2 on 2024-11-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_member_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='subagenda',
            name='bod_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_agendas', to='Dashboard.bodmeeting'),
        ),
    ]
