# Generated by Django 5.1.2 on 2024-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0030_subagenda_bod_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_sub_agenda',
            name='subagenda_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
