# Generated by Django 5.1.2 on 2026-08-27 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0039_alter_actionlog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodmeeting',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', help_text="Visible review status for this meeting's minutes/documents.", max_length=20),
        ),
        migrations.AddField(
            model_name='bodmeeting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodmeeting',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text="Who last moved this to 'Reviewed' or 'Approved'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
